import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import SiteHeader from "./components/SiteHeader";
import SCGLayout from "./components/SCGLayout";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/* 2. Colocas el script de Google dentro de <head> o directamente en el body */}
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5806249940542763"
          crossOrigin="anonymous"
          strategy="afterInteractive" // Controla cuándo se carga (opcional)
        />
      </head>
      <body className="min-h-full flex flex-col">
        <AntdRegistry>
          <SCGLayout>
            <div className="h-10 flex items-center px-4 bg-[#0F2C3E]">
              <span className="text-[#82919E]">Guía de Star Citizen</span>
            </div>
            <hr className="border-gray-700" />
            <SiteHeader />
            {children}
          </SCGLayout>
        </AntdRegistry>
      </body>
    </html>
  );
}
